image:
  - Visual Studio 2017

environment:
  global:
    NAME: sndfile
  matrix:
  - platform: x64
    HOST: x86_64-w64-mingw32
    ARCH: x86_64
    CFLAGS: -m64
    PATH: C:\msys64\mingw64\x86_64-w64-mingw32\bin\;C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
  - platform: x86
    HOST: i686-w64-mingw32
    ARCH: i686
    CFLAGS: -m32
    PATH: C:\msys64\mingw32\i686-w64-mingw32\bin\;C:\msys64\mingw32\bin\;C:\msys64\usr\bin\;$(PATH)

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - git submodule update --init --recursive


build_script:
  - set TARGET_ARTIFACT=lib%NAME%.dll.bodged-%ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - pacman -S --needed --noconfirm base-devel mingw-w64-%ARCH%-toolchain mingw-w64-%ARCH%-libogg mingw-w64-%ARCH%-libvorbis mingw-w64-%ARCH%-flac autogen nasm
  - sh -c "cd lib/ && make CFLAGS=%CFLAGS% INSTALL_XIPH_LIBS=true SUDO= clean build"
  - mv %APPVEYOR_BUILD_FOLDER%\lib\lib%NAME%.dll.bodged %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
